/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetointegrador;

/**
 *
 * @author SENAC NOITE
 */
public class CADASTROO extends javax.swing.JFrame {

    /**
     * Creates new form CADASTROO
     */
    public CADASTROO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel19 = new javax.swing.JPanel();
        medicamento = new javax.swing.JTextField();
        laboratorio = new javax.swing.JTextField();
        tipo = new javax.swing.JTextField();
        quantidade_entrada = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        bt_enviar = new javax.swing.JToggleButton();
        jLabel19 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 51, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(255, 153, 51));
        jPanel19.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-caneta-de-insulina-30.png")))); // NOI18N
        jPanel19.setForeground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        medicamento.setForeground(new java.awt.Color(0, 0, 0));
        medicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicamentoActionPerformed(evt);
            }
        });
        jPanel19.add(medicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 522, 34));

        laboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laboratorioActionPerformed(evt);
            }
        });
        jPanel19.add(laboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 121, 30));
        jPanel19.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 141, 30));

        quantidade_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidade_entradaActionPerformed(evt);
            }
        });
        jPanel19.add(quantidade_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 126, 30));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-pesquisar-30.png"))); // NOI18N
        jLabel15.setText("MEDICAMENTO");
        jPanel19.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        jLabel16.setText("LABORATORIO");
        jPanel19.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel17.setText("TIPO");
        jPanel19.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        jLabel18.setText("QTD- DE ENTRADA");
        jPanel19.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        bt_enviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/accept.png"))); // NOI18N
        bt_enviar.setText("ENVIAR");
        bt_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enviarActionPerformed(evt);
            }
        });
        jPanel19.add(bt_enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 172, 43));

        jLabel19.setText("CLASSE");
        jPanel19.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 133, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analgésicos/antitermicos", "Antiflamatórios", "Antibiótiocos e Antifungos Orais", "Antigripais/Xarope/Brocondilatadores / Antihistaminico e Inalatórios", "Corticoides Orais", "Injetaveis", "Antiparasitários", "Antihipertensivos", "Cardiotonicos", "Antigregantes e fins", "Antidiabeticogenicos", "Antilipemiantes", "Vasodilatadores", "Cerebrais e Perifericos", "Anticoncepcionais", "Repositórios hormonais", "Protetores Gastricos", "Antidiarredicos", "Antiemenicos", "Laxativos", "Antibióticos", "Antifungicos Orais", "Cremes Demartológicos e Creme Váginais", "Vitaminas", "Colírios", "Soluções Oftamologicas", "Psicotropicos", "Anticonvulsionantes", "Hiperplasia Prostatica" }));
        jComboBox1.setName(""); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel19.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 95, 30));

        getContentPane().add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 870, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void laboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laboratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laboratorioActionPerformed

    private void quantidade_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidade_entradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidade_entradaActionPerformed

    private void medicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicamentoActionPerformed

    private void bt_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enviarActionPerformed

 new ESTOQUE2().setVisible(true);
 setVisible(false);







        // TODO add your handling code here:
    }//GEN-LAST:event_bt_enviarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CADASTROO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CADASTROO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CADASTROO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CADASTROO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CADASTROO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bt_enviar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JTextField laboratorio;
    private javax.swing.JTextField medicamento;
    private javax.swing.JTextField quantidade_entrada;
    private javax.swing.JTextField tipo;
    // End of variables declaration//GEN-END:variables
}
