/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetointegrador;

import java.awt.CardLayout;

/**
 *
 * @author SENAC NOITE
 */
public class ESTOQUE2 extends javax.swing.JFrame {

    /**
     * Creates new form ESTOQUE2
     */
    public ESTOQUE2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        CLASSES = new javax.swing.JPanel();
        HOME = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        CLASSE1 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        CLASSE2 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTable19 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        CLASSE3 = new javax.swing.JPanel();
        jPanel45 = new javax.swing.JPanel();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTable20 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        CLASSE4 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTable21 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        CLASSE5 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        jScrollPane22 = new javax.swing.JScrollPane();
        jTable22 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        CLASSE6 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        jScrollPane23 = new javax.swing.JScrollPane();
        jTable23 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        CLASSE7 = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        jScrollPane24 = new javax.swing.JScrollPane();
        jTable24 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        CLASSE8 = new javax.swing.JPanel();
        jPanel50 = new javax.swing.JPanel();
        jScrollPane25 = new javax.swing.JScrollPane();
        jTable25 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        CLASSE9 = new javax.swing.JPanel();
        jPanel51 = new javax.swing.JPanel();
        jScrollPane26 = new javax.swing.JScrollPane();
        jTable26 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        CLASSE10 = new javax.swing.JPanel();
        jPanel52 = new javax.swing.JPanel();
        jScrollPane27 = new javax.swing.JScrollPane();
        jTable27 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        CLASSE11 = new javax.swing.JPanel();
        jPanel53 = new javax.swing.JPanel();
        jScrollPane28 = new javax.swing.JScrollPane();
        jTable28 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        CLASSE12 = new javax.swing.JPanel();
        jPanel54 = new javax.swing.JPanel();
        jScrollPane29 = new javax.swing.JScrollPane();
        jTable29 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        CLASSE13 = new javax.swing.JPanel();
        jPanel55 = new javax.swing.JPanel();
        jScrollPane30 = new javax.swing.JScrollPane();
        jTable30 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        CLASSE14 = new javax.swing.JPanel();
        jPanel56 = new javax.swing.JPanel();
        jScrollPane31 = new javax.swing.JScrollPane();
        jTable31 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        CLASSE15 = new javax.swing.JPanel();
        jPanel57 = new javax.swing.JPanel();
        jScrollPane32 = new javax.swing.JScrollPane();
        jTable32 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        CLASSE16 = new javax.swing.JPanel();
        jPanel58 = new javax.swing.JPanel();
        jScrollPane33 = new javax.swing.JScrollPane();
        jTable33 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        CLASSE17 = new javax.swing.JPanel();
        jPanel59 = new javax.swing.JPanel();
        jScrollPane34 = new javax.swing.JScrollPane();
        jTable34 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        CLASSE18 = new javax.swing.JPanel();
        jPanel60 = new javax.swing.JPanel();
        jScrollPane35 = new javax.swing.JScrollPane();
        jTable35 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        CLESSESS = new javax.swing.JMenu();
        ANALGÉSICOSANTITÉRMICOS = new javax.swing.JMenuItem();
        ANTIFLAMATORIOS = new javax.swing.JMenuItem();
        ANTIBIOTICOSEANTIFUNGICOSORAIS = new javax.swing.JMenuItem();
        ANTIGRIPAISXAROPEBRONCODILATADORESANTIHISTAMINICOEINALATORIOS = new javax.swing.JMenuItem();
        CORTICOIDESORAIS = new javax.swing.JMenuItem();
        INJETAVEIS = new javax.swing.JMenuItem();
        ANTIPARASITARIOS = new javax.swing.JMenuItem();
        ANTIHIPERTENSIVOSCARDIOTONICOSANTIAGREGANTESEAFINS = new javax.swing.JMenuItem();
        ANTIDIABETOGENICOS = new javax.swing.JMenuItem();
        ANTILIPEMIANTES = new javax.swing.JMenuItem();
        VASODILATADORESCEREBRAISEPERIFÉRICOS = new javax.swing.JMenuItem();
        ANTICONCEPCIONAISREPOSITORIOSHORMONAIS = new javax.swing.JMenuItem();
        PROTETORESGASTRICOSANTIDIARRETICOSANTIEMETICOSLAXATIVOSEAFINS = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        CREMESDERMATOLÓGICOSECREMESVAGINAIS = new javax.swing.JMenuItem();
        VITAMINAS = new javax.swing.JMenuItem();
        COLIRIOSSOLUCOESOFTALMOLOGICASSOLUCOESOTOLOGICAS = new javax.swing.JMenuItem();
        PSICOTROPICOSEANTICONVULSIVANTES = new javax.swing.JMenuItem();
        HIPERPLASIAPROSTÁTICA = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ESTOQUE");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CLASSES.setLayout(new java.awt.CardLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/farmacia.png"))); // NOI18N

        javax.swing.GroupLayout HOMELayout = new javax.swing.GroupLayout(HOME);
        HOME.setLayout(HOMELayout);
        HOMELayout.setHorizontalGroup(
            HOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HOMELayout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );
        HOMELayout.setVerticalGroup(
            HOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HOMELayout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        CLASSES.add(HOME, "card2");

        CLASSE1.setBackground(new java.awt.Color(204, 255, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MEDICAMENTO", "TIPO", "QUANTIDADE", "SAIDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setPreferredSize(new java.awt.Dimension(80, 80));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("ANALGÉSICOS / ANTITÉRMICOS");

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CLASSE1Layout = new javax.swing.GroupLayout(CLASSE1);
        CLASSE1.setLayout(CLASSE1Layout);
        CLASSE1Layout.setHorizontalGroup(
            CLASSE1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE1Layout.createSequentialGroup()
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CLASSE1Layout.setVerticalGroup(
            CLASSE1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE1Layout.createSequentialGroup()
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CLASSES.add(CLASSE1, "ANALGÉSICOS / ANTITÉRMICOS");

        jTable19.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MEDICAMENTO", "TIPO", "QUANTIDADE", "SAIDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable19.setPreferredSize(new java.awt.Dimension(80, 80));
        jScrollPane19.setViewportView(jTable19);

        jLabel2.setText("ANTIFLAMATORIOS");

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CLASSE2Layout = new javax.swing.GroupLayout(CLASSE2);
        CLASSE2.setLayout(CLASSE2Layout);
        CLASSE2Layout.setHorizontalGroup(
            CLASSE2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE2Layout.createSequentialGroup()
                .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CLASSE2Layout.setVerticalGroup(
            CLASSE2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE2Layout.createSequentialGroup()
                .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CLASSES.add(CLASSE2, "ANTIFLAMATORIOS");

        jTable20.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MEDICAMENTO", "TIPO", "QUANTIDADE", "SAIDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable20.setPreferredSize(new java.awt.Dimension(80, 80));
        jScrollPane20.setViewportView(jTable20);

        jLabel3.setText("ANTIBIOTICOS E ANTIFUNGICOS ORAIS");

        javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
        jPanel45.setLayout(jPanel45Layout);
        jPanel45Layout.setHorizontalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel45Layout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel45Layout.createSequentialGroup()
                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
        );
        jPanel45Layout.setVerticalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel45Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CLASSE3Layout = new javax.swing.GroupLayout(CLASSE3);
        CLASSE3.setLayout(CLASSE3Layout);
        CLASSE3Layout.setHorizontalGroup(
            CLASSE3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE3Layout.createSequentialGroup()
                .addComponent(jPanel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CLASSE3Layout.setVerticalGroup(
            CLASSE3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE3Layout.createSequentialGroup()
                .addComponent(jPanel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CLASSES.add(CLASSE3, "ANTIBIOTICOS E ANTIFUNGICOS ORAIS");

        jTable21.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MEDICAMENTO", "TIPO", "QUANTIDADE", "SAIDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable21.setPreferredSize(new java.awt.Dimension(80, 80));
        jScrollPane21.setViewportView(jTable21);

        jLabel4.setText("ANTIGRIPAIS / XAROPE / BRONCODILATADORES / ANTIHISTAMINICO E INALATORIOS");

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel46Layout.createSequentialGroup()
                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
            .addGroup(jPanel46Layout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel46Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CLASSE4Layout = new javax.swing.GroupLayout(CLASSE4);
        CLASSE4.setLayout(CLASSE4Layout);
        CLASSE4Layout.setHorizontalGroup(
            CLASSE4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE4Layout.createSequentialGroup()
                .addComponent(jPanel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CLASSE4Layout.setVerticalGroup(
            CLASSE4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE4Layout.createSequentialGroup()
                .addComponent(jPanel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CLASSES.add(CLASSE4, "ANTIGRIPAIS / XAROPE / BRONCODILATADORES / ANTIHISTAMINICO E INALATORIOS");

        jTable22.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MEDICAMENTO", "TIPO", "QUANTIDADE", "SAIDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable22.setPreferredSize(new java.awt.Dimension(80, 80));
        jScrollPane22.setViewportView(jTable22);

        jLabel5.setText("CORTICOIDES ORAIS  ");

        javax.swing.GroupLayout jPanel47Layout = new javax.swing.GroupLayout(jPanel47);
        jPanel47.setLayout(jPanel47Layout);
        jPanel47Layout.setHorizontalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel47Layout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel47Layout.createSequentialGroup()
                .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
        );
        jPanel47Layout.setVerticalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel47Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CLASSE5Layout = new javax.swing.GroupLayout(CLASSE5);
        CLASSE5.setLayout(CLASSE5Layout);
        CLASSE5Layout.setHorizontalGroup(
            CLASSE5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE5Layout.createSequentialGroup()
                .addComponent(jPanel47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CLASSE5Layout.setVerticalGroup(
            CLASSE5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE5Layout.createSequentialGroup()
                .addComponent(jPanel47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CLASSES.add(CLASSE5, "CORTICOIDES ORAIS");

        jTable23.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MEDICAMENTO", "TIPO", "QUANTIDADE", "SAIDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable23.setPreferredSize(new java.awt.Dimension(80, 80));
        jScrollPane23.setViewportView(jTable23);

        jLabel6.setText("INJETAVEIS");

        javax.swing.GroupLayout jPanel48Layout = new javax.swing.GroupLayout(jPanel48);
        jPanel48.setLayout(jPanel48Layout);
        jPanel48Layout.setHorizontalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel48Layout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel48Layout.createSequentialGroup()
                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
        );
        jPanel48Layout.setVerticalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel48Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CLASSE6Layout = new javax.swing.GroupLayout(CLASSE6);
        CLASSE6.setLayout(CLASSE6Layout);
        CLASSE6Layout.setHorizontalGroup(
            CLASSE6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE6Layout.createSequentialGroup()
                .addComponent(jPanel48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CLASSE6Layout.setVerticalGroup(
            CLASSE6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE6Layout.createSequentialGroup()
                .addComponent(jPanel48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CLASSES.add(CLASSE6, "INJETAVEIS");

        jTable24.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MEDICAMENTO", "TIPO", "QUANTIDADE", "SAIDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable24.setPreferredSize(new java.awt.Dimension(80, 80));
        jScrollPane24.setViewportView(jTable24);

        jLabel7.setText("ANTIPARASITARIOS");

        javax.swing.GroupLayout jPanel49Layout = new javax.swing.GroupLayout(jPanel49);
        jPanel49.setLayout(jPanel49Layout);
        jPanel49Layout.setHorizontalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel49Layout.createSequentialGroup()
                .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
            .addGroup(jPanel49Layout.createSequentialGroup()
                .addGap(534, 534, 534)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel49Layout.setVerticalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel49Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CLASSE7Layout = new javax.swing.GroupLayout(CLASSE7);
        CLASSE7.setLayout(CLASSE7Layout);
        CLASSE7Layout.setHorizontalGroup(
            CLASSE7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE7Layout.createSequentialGroup()
                .addComponent(jPanel49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CLASSE7Layout.setVerticalGroup(
            CLASSE7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE7Layout.createSequentialGroup()
                .addComponent(jPanel49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CLASSES.add(CLASSE7, "ANTIPARASITARIOS");

        jTable25.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MEDICAMENTO", "TIPO", "QUANTIDADE", "SAIDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable25.setPreferredSize(new java.awt.Dimension(80, 80));
        jScrollPane25.setViewportView(jTable25);

        jLabel8.setText("ANTIHIPERTENSIVOS / CARDIOTONICOS / ANTIAGREGANTES E AFINS");

        javax.swing.GroupLayout jPanel50Layout = new javax.swing.GroupLayout(jPanel50);
        jPanel50.setLayout(jPanel50Layout);
        jPanel50Layout.setHorizontalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel50Layout.createSequentialGroup()
                .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
            .addGroup(jPanel50Layout.createSequentialGroup()
                .addGap(443, 443, 443)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel50Layout.setVerticalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel50Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CLASSE8Layout = new javax.swing.GroupLayout(CLASSE8);
        CLASSE8.setLayout(CLASSE8Layout);
        CLASSE8Layout.setHorizontalGroup(
            CLASSE8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE8Layout.createSequentialGroup()
                .addComponent(jPanel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CLASSE8Layout.setVerticalGroup(
            CLASSE8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE8Layout.createSequentialGroup()
                .addComponent(jPanel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CLASSES.add(CLASSE8, "ANTIHIPERTENSIVOS / CARDIOTONICOS / ANTIAGREGANTES E AFINS");

        jTable26.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MEDICAMENTO", "TIPO", "QUANTIDADE", "SAIDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable26.setPreferredSize(new java.awt.Dimension(80, 80));
        jScrollPane26.setViewportView(jTable26);

        jLabel9.setText("ANTIDIABETOGENICOS");

        javax.swing.GroupLayout jPanel51Layout = new javax.swing.GroupLayout(jPanel51);
        jPanel51.setLayout(jPanel51Layout);
        jPanel51Layout.setHorizontalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel51Layout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel51Layout.createSequentialGroup()
                .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
        );
        jPanel51Layout.setVerticalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel51Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CLASSE9Layout = new javax.swing.GroupLayout(CLASSE9);
        CLASSE9.setLayout(CLASSE9Layout);
        CLASSE9Layout.setHorizontalGroup(
            CLASSE9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE9Layout.createSequentialGroup()
                .addComponent(jPanel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CLASSE9Layout.setVerticalGroup(
            CLASSE9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE9Layout.createSequentialGroup()
                .addComponent(jPanel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CLASSES.add(CLASSE9, "ANTIDIABETOGENICOS");

        jTable27.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MEDICAMENTO", "TIPO", "QUANTIDADE", "SAIDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable27.setPreferredSize(new java.awt.Dimension(80, 80));
        jScrollPane27.setViewportView(jTable27);

        jLabel10.setText("ANTILIPEMIANTES");

        javax.swing.GroupLayout jPanel52Layout = new javax.swing.GroupLayout(jPanel52);
        jPanel52.setLayout(jPanel52Layout);
        jPanel52Layout.setHorizontalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel52Layout.createSequentialGroup()
                .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
            .addGroup(jPanel52Layout.createSequentialGroup()
                .addGap(532, 532, 532)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel52Layout.setVerticalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel52Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CLASSE10Layout = new javax.swing.GroupLayout(CLASSE10);
        CLASSE10.setLayout(CLASSE10Layout);
        CLASSE10Layout.setHorizontalGroup(
            CLASSE10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE10Layout.createSequentialGroup()
                .addComponent(jPanel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CLASSE10Layout.setVerticalGroup(
            CLASSE10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE10Layout.createSequentialGroup()
                .addComponent(jPanel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CLASSES.add(CLASSE10, "ANTILIPEMIANTES");

        jTable28.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MEDICAMENTO", "TIPO", "QUANTIDADE", "SAIDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable28.setPreferredSize(new java.awt.Dimension(80, 80));
        jScrollPane28.setViewportView(jTable28);

        jLabel11.setText("VASODILATADORES CEREBRAIS E PERIFÉRICOS");

        javax.swing.GroupLayout jPanel53Layout = new javax.swing.GroupLayout(jPanel53);
        jPanel53.setLayout(jPanel53Layout);
        jPanel53Layout.setHorizontalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel53Layout.createSequentialGroup()
                .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
            .addGroup(jPanel53Layout.createSequentialGroup()
                .addGap(467, 467, 467)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel53Layout.setVerticalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel53Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CLASSE11Layout = new javax.swing.GroupLayout(CLASSE11);
        CLASSE11.setLayout(CLASSE11Layout);
        CLASSE11Layout.setHorizontalGroup(
            CLASSE11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE11Layout.createSequentialGroup()
                .addComponent(jPanel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CLASSE11Layout.setVerticalGroup(
            CLASSE11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE11Layout.createSequentialGroup()
                .addComponent(jPanel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CLASSES.add(CLASSE11, "VASODILATADORES CEREBRAIS E PERIFÉRICOS");

        jTable29.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MEDICAMENTO", "TIPO", "QUANTIDADE", "SAIDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable29.setPreferredSize(new java.awt.Dimension(80, 80));
        jScrollPane29.setViewportView(jTable29);

        jLabel12.setText("ANTICONCEPCIONAIS / REPOSITORIOS HORMONAIS");

        javax.swing.GroupLayout jPanel54Layout = new javax.swing.GroupLayout(jPanel54);
        jPanel54.setLayout(jPanel54Layout);
        jPanel54Layout.setHorizontalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel54Layout.createSequentialGroup()
                .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
            .addGroup(jPanel54Layout.createSequentialGroup()
                .addGap(394, 394, 394)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel54Layout.setVerticalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel54Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CLASSE12Layout = new javax.swing.GroupLayout(CLASSE12);
        CLASSE12.setLayout(CLASSE12Layout);
        CLASSE12Layout.setHorizontalGroup(
            CLASSE12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE12Layout.createSequentialGroup()
                .addComponent(jPanel54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CLASSE12Layout.setVerticalGroup(
            CLASSE12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE12Layout.createSequentialGroup()
                .addComponent(jPanel54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CLASSES.add(CLASSE12, "ANTICONCEPCIONAIS / REPOSITORIOS HORMONAIS");

        jTable30.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MEDICAMENTO", "TIPO", "QUANTIDADE", "SAIDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable30.setPreferredSize(new java.awt.Dimension(80, 80));
        jScrollPane30.setViewportView(jTable30);

        jLabel13.setText("PROTETORES GASTRICOS / ANTIDIARRETICOS / ANTIEMETICOS / LAXATIVOS E AFINS");

        javax.swing.GroupLayout jPanel55Layout = new javax.swing.GroupLayout(jPanel55);
        jPanel55.setLayout(jPanel55Layout);
        jPanel55Layout.setHorizontalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel55Layout.createSequentialGroup()
                .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
            .addGroup(jPanel55Layout.createSequentialGroup()
                .addGap(432, 432, 432)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel55Layout.setVerticalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel55Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CLASSE13Layout = new javax.swing.GroupLayout(CLASSE13);
        CLASSE13.setLayout(CLASSE13Layout);
        CLASSE13Layout.setHorizontalGroup(
            CLASSE13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE13Layout.createSequentialGroup()
                .addComponent(jPanel55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CLASSE13Layout.setVerticalGroup(
            CLASSE13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE13Layout.createSequentialGroup()
                .addComponent(jPanel55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CLASSES.add(CLASSE13, "PROTETORES GASTRICOS / ANTIDIARRETICOS / ANTIEMETICOS / LAXATIVOS E AFINS");

        jTable31.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MEDICAMENTO", "TIPO", "QUANTIDADE", "SAIDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable31.setPreferredSize(new java.awt.Dimension(80, 80));
        jScrollPane31.setViewportView(jTable31);

        jLabel14.setText("CREMES DERMATOLÓGICOS E CREMES VAGINAIS");

        javax.swing.GroupLayout jPanel56Layout = new javax.swing.GroupLayout(jPanel56);
        jPanel56.setLayout(jPanel56Layout);
        jPanel56Layout.setHorizontalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel56Layout.createSequentialGroup()
                .addComponent(jScrollPane31, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
            .addGroup(jPanel56Layout.createSequentialGroup()
                .addGap(494, 494, 494)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel56Layout.setVerticalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel56Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane31, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CLASSE14Layout = new javax.swing.GroupLayout(CLASSE14);
        CLASSE14.setLayout(CLASSE14Layout);
        CLASSE14Layout.setHorizontalGroup(
            CLASSE14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE14Layout.createSequentialGroup()
                .addComponent(jPanel56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CLASSE14Layout.setVerticalGroup(
            CLASSE14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE14Layout.createSequentialGroup()
                .addComponent(jPanel56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CLASSES.add(CLASSE14, "CREMES DERMATOLÓGICOS E CREMES VAGINAIS");

        jTable32.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MEDICAMENTO", "TIPO", "QUANTIDADE", "SAIDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable32.setPreferredSize(new java.awt.Dimension(80, 80));
        jScrollPane32.setViewportView(jTable32);

        jLabel15.setText("VITAMINAS");

        javax.swing.GroupLayout jPanel57Layout = new javax.swing.GroupLayout(jPanel57);
        jPanel57.setLayout(jPanel57Layout);
        jPanel57Layout.setHorizontalGroup(
            jPanel57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel57Layout.createSequentialGroup()
                .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
            .addGroup(jPanel57Layout.createSequentialGroup()
                .addGap(553, 553, 553)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel57Layout.setVerticalGroup(
            jPanel57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel57Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CLASSE15Layout = new javax.swing.GroupLayout(CLASSE15);
        CLASSE15.setLayout(CLASSE15Layout);
        CLASSE15Layout.setHorizontalGroup(
            CLASSE15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE15Layout.createSequentialGroup()
                .addComponent(jPanel57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CLASSE15Layout.setVerticalGroup(
            CLASSE15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE15Layout.createSequentialGroup()
                .addComponent(jPanel57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CLASSES.add(CLASSE15, "VITAMINAS");

        jTable33.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MEDICAMENTO", "TIPO", "QUANTIDADE", "SAIDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable33.setPreferredSize(new java.awt.Dimension(80, 80));
        jScrollPane33.setViewportView(jTable33);

        jLabel16.setText("COLIRIOS / SOLUCOES OFTALMOLOGICAS / SOLUCOES OTOLOGICAS");

        javax.swing.GroupLayout jPanel58Layout = new javax.swing.GroupLayout(jPanel58);
        jPanel58.setLayout(jPanel58Layout);
        jPanel58Layout.setHorizontalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel58Layout.createSequentialGroup()
                .addComponent(jScrollPane33, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
            .addGroup(jPanel58Layout.createSequentialGroup()
                .addGap(492, 492, 492)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel58Layout.setVerticalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel58Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane33, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CLASSE16Layout = new javax.swing.GroupLayout(CLASSE16);
        CLASSE16.setLayout(CLASSE16Layout);
        CLASSE16Layout.setHorizontalGroup(
            CLASSE16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE16Layout.createSequentialGroup()
                .addComponent(jPanel58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CLASSE16Layout.setVerticalGroup(
            CLASSE16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE16Layout.createSequentialGroup()
                .addComponent(jPanel58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CLASSES.add(CLASSE16, "COLIRIOS / SOLUCOES OFTALMOLOGICAS / SOLUCOES OTOLOGICAS");

        jTable34.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MEDICAMENTO", "TIPO", "QUANTIDADE", "SAIDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable34.setPreferredSize(new java.awt.Dimension(80, 80));
        jScrollPane34.setViewportView(jTable34);

        jLabel17.setText("PSICOTROPICOS E ANTICONVULSIVANTES");

        javax.swing.GroupLayout jPanel59Layout = new javax.swing.GroupLayout(jPanel59);
        jPanel59.setLayout(jPanel59Layout);
        jPanel59Layout.setHorizontalGroup(
            jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel59Layout.createSequentialGroup()
                .addGroup(jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel59Layout.createSequentialGroup()
                        .addGap(511, 511, 511)
                        .addComponent(jLabel17))
                    .addGroup(jPanel59Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane34, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(859, Short.MAX_VALUE))
        );
        jPanel59Layout.setVerticalGroup(
            jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel59Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane34, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(535, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CLASSE17Layout = new javax.swing.GroupLayout(CLASSE17);
        CLASSE17.setLayout(CLASSE17Layout);
        CLASSE17Layout.setHorizontalGroup(
            CLASSE17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE17Layout.createSequentialGroup()
                .addComponent(jPanel59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CLASSE17Layout.setVerticalGroup(
            CLASSE17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE17Layout.createSequentialGroup()
                .addComponent(jPanel59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CLASSES.add(CLASSE17, "PSICOTROPICOS E ANTICONVULSIVANTES");

        jTable35.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MEDICAMENTO", "TIPO", "QUANTIDADE", "SAIDA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable35.setPreferredSize(new java.awt.Dimension(80, 80));
        jScrollPane35.setViewportView(jTable35);

        jLabel18.setText("ANALGÉSICOS / ANTITÉRMICOS");

        javax.swing.GroupLayout jPanel60Layout = new javax.swing.GroupLayout(jPanel60);
        jPanel60.setLayout(jPanel60Layout);
        jPanel60Layout.setHorizontalGroup(
            jPanel60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel60Layout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel60Layout.createSequentialGroup()
                .addComponent(jScrollPane35, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
        );
        jPanel60Layout.setVerticalGroup(
            jPanel60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel60Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane35, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CLASSE18Layout = new javax.swing.GroupLayout(CLASSE18);
        CLASSE18.setLayout(CLASSE18Layout);
        CLASSE18Layout.setHorizontalGroup(
            CLASSE18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE18Layout.createSequentialGroup()
                .addComponent(jPanel60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CLASSE18Layout.setVerticalGroup(
            CLASSE18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLASSE18Layout.createSequentialGroup()
                .addComponent(jPanel60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        CLASSES.add(CLASSE18, "HIPERPLASIA PROSTÁTICA");

        getContentPane().add(CLASSES, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 720));

        CLESSESS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-cardápio-30.png"))); // NOI18N
        CLESSESS.setText("CLASSES");

        ANALGÉSICOSANTITÉRMICOS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ANALGÉSICOSANTITÉRMICOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-mão-com-uma-pílula-30.png"))); // NOI18N
        ANALGÉSICOSANTITÉRMICOS.setText("ANALGÉSICOS / ANTITÉRMICOS");
        ANALGÉSICOSANTITÉRMICOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANALGÉSICOSANTITÉRMICOSActionPerformed(evt);
            }
        });
        CLESSESS.add(ANALGÉSICOSANTITÉRMICOS);

        ANTIFLAMATORIOS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ANTIFLAMATORIOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-mão-com-uma-pílula-30.png"))); // NOI18N
        ANTIFLAMATORIOS.setText("ANTIFLAMATORIOS");
        ANTIFLAMATORIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANTIFLAMATORIOSActionPerformed(evt);
            }
        });
        CLESSESS.add(ANTIFLAMATORIOS);

        ANTIBIOTICOSEANTIFUNGICOSORAIS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ANTIBIOTICOSEANTIFUNGICOSORAIS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-mão-com-uma-pílula-30.png"))); // NOI18N
        ANTIBIOTICOSEANTIFUNGICOSORAIS.setText("ANTIBIOTICOS E ANTIFUNGICOS ORAIS");
        ANTIBIOTICOSEANTIFUNGICOSORAIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANTIBIOTICOSEANTIFUNGICOSORAISActionPerformed(evt);
            }
        });
        CLESSESS.add(ANTIBIOTICOSEANTIFUNGICOSORAIS);

        ANTIGRIPAISXAROPEBRONCODILATADORESANTIHISTAMINICOEINALATORIOS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ANTIGRIPAISXAROPEBRONCODILATADORESANTIHISTAMINICOEINALATORIOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-mão-com-uma-pílula-30.png"))); // NOI18N
        ANTIGRIPAISXAROPEBRONCODILATADORESANTIHISTAMINICOEINALATORIOS.setText("ANTIGRIPAIS / XAROPE / BRONCODILATADORES / ANTIHISTAMINICO E INALATORIOS");
        ANTIGRIPAISXAROPEBRONCODILATADORESANTIHISTAMINICOEINALATORIOS.setBorderPainted(false);
        ANTIGRIPAISXAROPEBRONCODILATADORESANTIHISTAMINICOEINALATORIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANTIGRIPAISXAROPEBRONCODILATADORESANTIHISTAMINICOEINALATORIOSActionPerformed(evt);
            }
        });
        CLESSESS.add(ANTIGRIPAISXAROPEBRONCODILATADORESANTIHISTAMINICOEINALATORIOS);

        CORTICOIDESORAIS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CORTICOIDESORAIS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-mão-com-uma-pílula-30.png"))); // NOI18N
        CORTICOIDESORAIS.setText("CORTICOIDES ORAIS ");
        CORTICOIDESORAIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CORTICOIDESORAISActionPerformed(evt);
            }
        });
        CLESSESS.add(CORTICOIDESORAIS);

        INJETAVEIS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        INJETAVEIS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-mão-com-uma-pílula-30.png"))); // NOI18N
        INJETAVEIS.setText(" INJETAVEIS");
        INJETAVEIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INJETAVEISActionPerformed(evt);
            }
        });
        CLESSESS.add(INJETAVEIS);

        ANTIPARASITARIOS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ANTIPARASITARIOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-mão-com-uma-pílula-30.png"))); // NOI18N
        ANTIPARASITARIOS.setText("ANTIPARASITARIOS");
        ANTIPARASITARIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANTIPARASITARIOSActionPerformed(evt);
            }
        });
        CLESSESS.add(ANTIPARASITARIOS);

        ANTIHIPERTENSIVOSCARDIOTONICOSANTIAGREGANTESEAFINS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ANTIHIPERTENSIVOSCARDIOTONICOSANTIAGREGANTESEAFINS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-mão-com-uma-pílula-30.png"))); // NOI18N
        ANTIHIPERTENSIVOSCARDIOTONICOSANTIAGREGANTESEAFINS.setText("ANTIHIPERTENSIVOS / CARDIOTONICOS / ANTIAGREGANTES E AFINS");
        ANTIHIPERTENSIVOSCARDIOTONICOSANTIAGREGANTESEAFINS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANTIHIPERTENSIVOSCARDIOTONICOSANTIAGREGANTESEAFINSActionPerformed(evt);
            }
        });
        CLESSESS.add(ANTIHIPERTENSIVOSCARDIOTONICOSANTIAGREGANTESEAFINS);

        ANTIDIABETOGENICOS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ANTIDIABETOGENICOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-mão-com-uma-pílula-30.png"))); // NOI18N
        ANTIDIABETOGENICOS.setText("ANTIDIABETOGENICOS");
        ANTIDIABETOGENICOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANTIDIABETOGENICOSActionPerformed(evt);
            }
        });
        CLESSESS.add(ANTIDIABETOGENICOS);

        ANTILIPEMIANTES.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ANTILIPEMIANTES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-mão-com-uma-pílula-30.png"))); // NOI18N
        ANTILIPEMIANTES.setText("ANTILIPEMIANTES");
        ANTILIPEMIANTES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANTILIPEMIANTESActionPerformed(evt);
            }
        });
        CLESSESS.add(ANTILIPEMIANTES);

        VASODILATADORESCEREBRAISEPERIFÉRICOS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        VASODILATADORESCEREBRAISEPERIFÉRICOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-mão-com-uma-pílula-30.png"))); // NOI18N
        VASODILATADORESCEREBRAISEPERIFÉRICOS.setText("VASODILATADORES CEREBRAIS E PERIFÉRICOS");
        VASODILATADORESCEREBRAISEPERIFÉRICOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VASODILATADORESCEREBRAISEPERIFÉRICOSActionPerformed(evt);
            }
        });
        CLESSESS.add(VASODILATADORESCEREBRAISEPERIFÉRICOS);

        ANTICONCEPCIONAISREPOSITORIOSHORMONAIS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ANTICONCEPCIONAISREPOSITORIOSHORMONAIS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-mão-com-uma-pílula-30.png"))); // NOI18N
        ANTICONCEPCIONAISREPOSITORIOSHORMONAIS.setText("ANTICONCEPCIONAIS / REPOSITORIOS HORMONAIS");
        ANTICONCEPCIONAISREPOSITORIOSHORMONAIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANTICONCEPCIONAISREPOSITORIOSHORMONAISActionPerformed(evt);
            }
        });
        CLESSESS.add(ANTICONCEPCIONAISREPOSITORIOSHORMONAIS);

        PROTETORESGASTRICOSANTIDIARRETICOSANTIEMETICOSLAXATIVOSEAFINS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PROTETORESGASTRICOSANTIDIARRETICOSANTIEMETICOSLAXATIVOSEAFINS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-mão-com-uma-pílula-30.png"))); // NOI18N
        PROTETORESGASTRICOSANTIDIARRETICOSANTIEMETICOSLAXATIVOSEAFINS.setText("PROTETORES GASTRICOS / ANTIDIARRETICOS / ANTIEMETICOS / LAXATIVOS E AFINS");
        PROTETORESGASTRICOSANTIDIARRETICOSANTIEMETICOSLAXATIVOSEAFINS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROTETORESGASTRICOSANTIDIARRETICOSANTIEMETICOSLAXATIVOSEAFINSActionPerformed(evt);
            }
        });
        CLESSESS.add(PROTETORESGASTRICOSANTIDIARRETICOSANTIEMETICOSLAXATIVOSEAFINS);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-mão-com-uma-pílula-30.png"))); // NOI18N
        jMenuItem3.setText("ANTIBIOTICOS E ANTIFUNGICOS ORAIS");
        CLESSESS.add(jMenuItem3);

        CREMESDERMATOLÓGICOSECREMESVAGINAIS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CREMESDERMATOLÓGICOSECREMESVAGINAIS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-mão-com-uma-pílula-30.png"))); // NOI18N
        CREMESDERMATOLÓGICOSECREMESVAGINAIS.setText("CREMES DERMATOLÓGICOS E CREMES VAGINAIS");
        CREMESDERMATOLÓGICOSECREMESVAGINAIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREMESDERMATOLÓGICOSECREMESVAGINAISActionPerformed(evt);
            }
        });
        CLESSESS.add(CREMESDERMATOLÓGICOSECREMESVAGINAIS);

        VITAMINAS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        VITAMINAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-mão-com-uma-pílula-30.png"))); // NOI18N
        VITAMINAS.setText("VITAMINAS");
        VITAMINAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VITAMINASActionPerformed(evt);
            }
        });
        CLESSESS.add(VITAMINAS);

        COLIRIOSSOLUCOESOFTALMOLOGICASSOLUCOESOTOLOGICAS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        COLIRIOSSOLUCOESOFTALMOLOGICASSOLUCOESOTOLOGICAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-mão-com-uma-pílula-30.png"))); // NOI18N
        COLIRIOSSOLUCOESOFTALMOLOGICASSOLUCOESOTOLOGICAS.setText("COLIRIOS / SOLUCOES OFTALMOLOGICAS / SOLUCOES OTOLOGICAS");
        COLIRIOSSOLUCOESOFTALMOLOGICASSOLUCOESOTOLOGICAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COLIRIOSSOLUCOESOFTALMOLOGICASSOLUCOESOTOLOGICASActionPerformed(evt);
            }
        });
        CLESSESS.add(COLIRIOSSOLUCOESOFTALMOLOGICASSOLUCOESOTOLOGICAS);

        PSICOTROPICOSEANTICONVULSIVANTES.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PSICOTROPICOSEANTICONVULSIVANTES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-mão-com-uma-pílula-30.png"))); // NOI18N
        PSICOTROPICOSEANTICONVULSIVANTES.setText("PSICOTROPICOS E ANTICONVULSIVANTES");
        PSICOTROPICOSEANTICONVULSIVANTES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSICOTROPICOSEANTICONVULSIVANTESActionPerformed(evt);
            }
        });
        CLESSESS.add(PSICOTROPICOSEANTICONVULSIVANTES);

        HIPERPLASIAPROSTÁTICA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HIPERPLASIAPROSTÁTICA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/icons8-mão-com-uma-pílula-30.png"))); // NOI18N
        HIPERPLASIAPROSTÁTICA.setText("HIPERPLASIA PROSTÁTICA");
        HIPERPLASIAPROSTÁTICA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HIPERPLASIAPROSTÁTICAActionPerformed(evt);
            }
        });
        CLESSESS.add(HIPERPLASIAPROSTÁTICA);

        jMenuBar1.add(CLESSESS);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ANALGÉSICOSANTITÉRMICOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANALGÉSICOSANTITÉRMICOSActionPerformed
       CardLayout cl = (CardLayout)CLASSES.getLayout();
       cl.show(CLASSES,"ANALGÉSICOS / ANTITÉRMICOS");
    }//GEN-LAST:event_ANALGÉSICOSANTITÉRMICOSActionPerformed

    private void ANTIGRIPAISXAROPEBRONCODILATADORESANTIHISTAMINICOEINALATORIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANTIGRIPAISXAROPEBRONCODILATADORESANTIHISTAMINICOEINALATORIOSActionPerformed
     
        CardLayout cl = (CardLayout)CLASSES.getLayout();
       cl.show(CLASSES,"ANTIGRIPAIS / XAROPE / BRONCODILATADORES / ANTIHISTAMINICO E INALATORIOS");
    }//GEN-LAST:event_ANTIGRIPAISXAROPEBRONCODILATADORESANTIHISTAMINICOEINALATORIOSActionPerformed

    private void ANTIDIABETOGENICOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANTIDIABETOGENICOSActionPerformed
          CardLayout cl = (CardLayout)CLASSES.getLayout();
       cl.show(CLASSES,"ANTIDIABETOGENICOS");
    }//GEN-LAST:event_ANTIDIABETOGENICOSActionPerformed

    private void COLIRIOSSOLUCOESOFTALMOLOGICASSOLUCOESOTOLOGICASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COLIRIOSSOLUCOESOFTALMOLOGICASSOLUCOESOTOLOGICASActionPerformed
    CardLayout cl = (CardLayout)CLASSES.getLayout();
       cl.show(CLASSES,"COLIRIOS / SOLUCOES OFTALMOLOGICAS / SOLUCOES OTOLOGICAS");
    }//GEN-LAST:event_COLIRIOSSOLUCOESOFTALMOLOGICASSOLUCOESOTOLOGICASActionPerformed

    private void HIPERPLASIAPROSTÁTICAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HIPERPLASIAPROSTÁTICAActionPerformed
    
        
    CardLayout cl = (CardLayout)CLASSES.getLayout();
       cl.show(CLASSES,"HIPERPLASIA PROSTÁTICA");

    }//GEN-LAST:event_HIPERPLASIAPROSTÁTICAActionPerformed

    private void CORTICOIDESORAISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CORTICOIDESORAISActionPerformed
      CardLayout cl = (CardLayout)CLASSES.getLayout();
       cl.show(CLASSES,"CORTICOIDES ORAIS ");
    }//GEN-LAST:event_CORTICOIDESORAISActionPerformed

    private void CREMESDERMATOLÓGICOSECREMESVAGINAISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREMESDERMATOLÓGICOSECREMESVAGINAISActionPerformed
          CardLayout cl = (CardLayout)CLASSES.getLayout();
       cl.show(CLASSES,"CREMES DERMATOLÓGICOS E CREMES VAGINAIS");
    }//GEN-LAST:event_CREMESDERMATOLÓGICOSECREMESVAGINAISActionPerformed

    private void PSICOTROPICOSEANTICONVULSIVANTESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSICOTROPICOSEANTICONVULSIVANTESActionPerformed

          CardLayout cl = (CardLayout)CLASSES.getLayout();
       cl.show(CLASSES,"PSICOTROPICOS E ANTICONVULSIVANTES");




    }//GEN-LAST:event_PSICOTROPICOSEANTICONVULSIVANTESActionPerformed

    private void ANTIFLAMATORIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANTIFLAMATORIOSActionPerformed
        CardLayout cl = (CardLayout)CLASSES.getLayout();
       cl.show(CLASSES,"ANTIFLAMATORIOS");
    }//GEN-LAST:event_ANTIFLAMATORIOSActionPerformed

    private void ANTIBIOTICOSEANTIFUNGICOSORAISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANTIBIOTICOSEANTIFUNGICOSORAISActionPerformed
        CardLayout cl = (CardLayout)CLASSES.getLayout();
       cl.show(CLASSES,"ANTIBIOTICOS E ANTIFUNGICOS ORAIS");
    
    }//GEN-LAST:event_ANTIBIOTICOSEANTIFUNGICOSORAISActionPerformed

    private void INJETAVEISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INJETAVEISActionPerformed
     CardLayout cl = (CardLayout)CLASSES.getLayout();
       cl.show(CLASSES,"INJETAVEIS");
       
    }//GEN-LAST:event_INJETAVEISActionPerformed

    private void ANTIPARASITARIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANTIPARASITARIOSActionPerformed
      CardLayout cl = (CardLayout)CLASSES.getLayout();
       cl.show(CLASSES,"ANTIPARASITORIOS");
    }//GEN-LAST:event_ANTIPARASITARIOSActionPerformed

    private void ANTIHIPERTENSIVOSCARDIOTONICOSANTIAGREGANTESEAFINSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANTIHIPERTENSIVOSCARDIOTONICOSANTIAGREGANTESEAFINSActionPerformed
     CardLayout cl = (CardLayout)CLASSES.getLayout();
       cl.show(CLASSES,"ANTIHIPERTENSIVOS / CARDIOTONICOS / ANTIAGREGANTES E AFINS");
   
    }//GEN-LAST:event_ANTIHIPERTENSIVOSCARDIOTONICOSANTIAGREGANTESEAFINSActionPerformed

    private void ANTILIPEMIANTESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANTILIPEMIANTESActionPerformed
      
     CardLayout cl = (CardLayout)CLASSES.getLayout();
       cl.show(CLASSES,"ANTILIPEMIANTES");
    }//GEN-LAST:event_ANTILIPEMIANTESActionPerformed

    private void VASODILATADORESCEREBRAISEPERIFÉRICOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VASODILATADORESCEREBRAISEPERIFÉRICOSActionPerformed
      
     CardLayout cl = (CardLayout)CLASSES.getLayout();
       cl.show(CLASSES,"VASODILATADORES CEREBRAIS E PERIFÉRICOS");
     
    }//GEN-LAST:event_VASODILATADORESCEREBRAISEPERIFÉRICOSActionPerformed

    private void ANTICONCEPCIONAISREPOSITORIOSHORMONAISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANTICONCEPCIONAISREPOSITORIOSHORMONAISActionPerformed
     CardLayout cl = (CardLayout)CLASSES.getLayout();
       cl.show(CLASSES,"VASODILATADORES CEREBRAIS E PERIFÉRICOS");
      
    }//GEN-LAST:event_ANTICONCEPCIONAISREPOSITORIOSHORMONAISActionPerformed

    private void PROTETORESGASTRICOSANTIDIARRETICOSANTIEMETICOSLAXATIVOSEAFINSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROTETORESGASTRICOSANTIDIARRETICOSANTIEMETICOSLAXATIVOSEAFINSActionPerformed
     CardLayout cl = (CardLayout)CLASSES.getLayout();
       cl.show(CLASSES,"PROTETORES GASTRICOS / ANTIDIARRETICOS / ANTIEMETICOS / LAXATIVOS E AFINS");
       
    }//GEN-LAST:event_PROTETORESGASTRICOSANTIDIARRETICOSANTIEMETICOSLAXATIVOSEAFINSActionPerformed

    private void VITAMINASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VITAMINASActionPerformed
     CardLayout cl = (CardLayout)CLASSES.getLayout();
       cl.show(CLASSES,"VITAMINAS");
       
        // TODO add your handling code here:
    }//GEN-LAST:event_VITAMINASActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ESTOQUE2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ESTOQUE2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ESTOQUE2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ESTOQUE2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ESTOQUE2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ANALGÉSICOSANTITÉRMICOS;
    private javax.swing.JMenuItem ANTIBIOTICOSEANTIFUNGICOSORAIS;
    private javax.swing.JMenuItem ANTICONCEPCIONAISREPOSITORIOSHORMONAIS;
    private javax.swing.JMenuItem ANTIDIABETOGENICOS;
    private javax.swing.JMenuItem ANTIFLAMATORIOS;
    private javax.swing.JMenuItem ANTIGRIPAISXAROPEBRONCODILATADORESANTIHISTAMINICOEINALATORIOS;
    private javax.swing.JMenuItem ANTIHIPERTENSIVOSCARDIOTONICOSANTIAGREGANTESEAFINS;
    private javax.swing.JMenuItem ANTILIPEMIANTES;
    private javax.swing.JMenuItem ANTIPARASITARIOS;
    private javax.swing.JPanel CLASSE1;
    private javax.swing.JPanel CLASSE10;
    private javax.swing.JPanel CLASSE11;
    private javax.swing.JPanel CLASSE12;
    private javax.swing.JPanel CLASSE13;
    private javax.swing.JPanel CLASSE14;
    private javax.swing.JPanel CLASSE15;
    private javax.swing.JPanel CLASSE16;
    private javax.swing.JPanel CLASSE17;
    private javax.swing.JPanel CLASSE18;
    private javax.swing.JPanel CLASSE2;
    private javax.swing.JPanel CLASSE3;
    private javax.swing.JPanel CLASSE4;
    private javax.swing.JPanel CLASSE5;
    private javax.swing.JPanel CLASSE6;
    private javax.swing.JPanel CLASSE7;
    private javax.swing.JPanel CLASSE8;
    private javax.swing.JPanel CLASSE9;
    private javax.swing.JPanel CLASSES;
    private javax.swing.JMenu CLESSESS;
    private javax.swing.JMenuItem COLIRIOSSOLUCOESOFTALMOLOGICASSOLUCOESOTOLOGICAS;
    private javax.swing.JMenuItem CORTICOIDESORAIS;
    private javax.swing.JMenuItem CREMESDERMATOLÓGICOSECREMESVAGINAIS;
    private javax.swing.JMenuItem HIPERPLASIAPROSTÁTICA;
    private javax.swing.JPanel HOME;
    private javax.swing.JMenuItem INJETAVEIS;
    private javax.swing.JMenuItem PROTETORESGASTRICOSANTIDIARRETICOSANTIEMETICOSLAXATIVOSEAFINS;
    private javax.swing.JMenuItem PSICOTROPICOSEANTICONVULSIVANTES;
    private javax.swing.JMenuItem VASODILATADORESCEREBRAISEPERIFÉRICOS;
    private javax.swing.JMenuItem VITAMINAS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane33;
    private javax.swing.JScrollPane jScrollPane34;
    private javax.swing.JScrollPane jScrollPane35;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable19;
    private javax.swing.JTable jTable20;
    private javax.swing.JTable jTable21;
    private javax.swing.JTable jTable22;
    private javax.swing.JTable jTable23;
    private javax.swing.JTable jTable24;
    private javax.swing.JTable jTable25;
    private javax.swing.JTable jTable26;
    private javax.swing.JTable jTable27;
    private javax.swing.JTable jTable28;
    private javax.swing.JTable jTable29;
    private javax.swing.JTable jTable30;
    private javax.swing.JTable jTable31;
    private javax.swing.JTable jTable32;
    private javax.swing.JTable jTable33;
    private javax.swing.JTable jTable34;
    private javax.swing.JTable jTable35;
    // End of variables declaration//GEN-END:variables
}
