/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package panels;

import connection.TabelasDB;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.*;
import javax.swing.table.DefaultTableModel;
import modelo.FarmStrings;
import panels.MENU1;
/**
 *
 * @author jmpla
 */
public class Estoque extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
   public Estoque() {
        initComponents();
        
            this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Galery/icon2.png")).getImage());
        limparDesabilitarCampos(); //inicializa a tela com os campos vazios e desabilitados
        atualizaTabela(new TabelasDB()); //
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelJanelaEscola = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelTabela = new javax.swing.JScrollPane();
        tabelaEscola = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        CADASTRO1 = new javax.swing.JMenuItem();
        SAIDAS = new javax.swing.JMenuItem();
        CADASTRO = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelJanelaEscola.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painelJanelaEscola.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelJanelaEscola.setMinimumSize(new java.awt.Dimension(1280, 720));
        painelJanelaEscola.setName(""); // NOI18N
        painelJanelaEscola.setPreferredSize(new java.awt.Dimension(1280, 720));
        painelJanelaEscola.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tabela de Estoque");
        painelJanelaEscola.add(jLabel1);
        jLabel1.setBounds(630, 40, 380, 32);

        painelTabela.setBackground(new java.awt.Color(0, 0, 0));
        painelTabela.setDoubleBuffered(true);

        tabelaEscola.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Remédio", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        painelTabela.setViewportView(tabelaEscola);

        painelJanelaEscola.add(painelTabela);
        painelTabela.setBounds(260, 70, 970, 560);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galery/logo.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 10, 130, 130);

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Farmácia do Bem");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 140, 130, 15);

        painelJanelaEscola.add(jPanel1);
        jPanel1.setBounds(0, 0, 210, 720);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galery/Fundo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        painelJanelaEscola.add(jLabel2);
        jLabel2.setBounds(210, 0, 1070, 720);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1.setForeground(new java.awt.Color(48, 50, 52));
        jMenuBar1.setRequestFocusEnabled(false);

        jMenu3.setForeground(new java.awt.Color(48, 50, 52));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galery/icons8-cardápio-30.png"))); // NOI18N

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galery/icons8-comprimidos-30.png"))); // NOI18N
        jMenu2.setText("MEDICAMENTOS");

        CADASTRO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galery/icons8-add-product-20.png"))); // NOI18N
        CADASTRO1.setText("CADASTRO");
        CADASTRO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CADASTRO1ActionPerformed(evt);
            }
        });
        jMenu2.add(CADASTRO1);

        SAIDAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galery/icons8-comprar-20.png"))); // NOI18N
        SAIDAS.setText("SAIDAS");
        SAIDAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIDASActionPerformed(evt);
            }
        });
        jMenu2.add(SAIDAS);

        jMenu3.add(jMenu2);

        CADASTRO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Galery/icons8-página-inicial-30.png"))); // NOI18N
        CADASTRO.setText("INÍCIO");
        CADASTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CADASTROActionPerformed(evt);
            }
        });
        jMenu3.add(CADASTRO);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelJanelaEscola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelJanelaEscola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      private void atualizaTabela(TabelasDB escolaDao)
    {
        try
        {
            
            
            limparTabela();
            
            ArrayList<FarmStrings> listaFarmacia;
            listaFarmacia = escolaDao.consultar(); //consulta todos os registros da tabela Escola
            
            //Resgata o modelo da tabela            
            DefaultTableModel modeloTabela = (DefaultTableModel) tabelaEscola.getModel();

            for(FarmStrings escola : listaFarmacia)
            {
                //adiciona em cada linha da tabela da tela o conteúdo de cada posição da listaEscolas
                modeloTabela.addRow(new String[]{Integer.toString(escola.getIdEscola()), escola.getRm(),
                Integer.toString(escola.getQtd(), escola.getSaida())});
            }
            
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado:\n" + ex.getMessage(), "ERRO!", ERROR_MESSAGE);
        }
    }
   
     private void limparTabela()
    {
        //percorre a tabela e exclui todas as linhas
        while(tabelaEscola.getRowCount() > 0) 
        {
            DefaultTableModel dm = (DefaultTableModel) tabelaEscola.getModel();
            dm.getDataVector().removeAllElements();
        }
    }
     private void limparDesabilitarCampos()
    {
        //limpando todos os campos textos
    
      
    }
    private void CADASTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CADASTROActionPerformed
        new MENU1().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_CADASTROActionPerformed

    private void SAIDASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIDASActionPerformed
        new Saida().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_SAIDASActionPerformed

    private void CADASTRO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CADASTRO1ActionPerformed
        new NewJFrame().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_CADASTRO1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estoque().setVisible(true);
            }
        });
        
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CADASTRO;
    private javax.swing.JMenuItem CADASTRO1;
    private javax.swing.JMenuItem SAIDAS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel painelJanelaEscola;
    private javax.swing.JScrollPane painelTabela;
    public javax.swing.JTable tabelaEscola;
    // End of variables declaration//GEN-END:variables
}
